/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jtableguidemo;
import java.util.* ;
import java.io.* ;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class UIMain extends javax.swing.JFrame {
    public List<Employee>UserList = new ArrayList<>() ;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UIMain.class.getName());
    
    
    
    /**
     * Creates new form UIMain
     */
    public UIMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtPhoneNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        txtJobPosition = new javax.swing.JTextField();
        btnAddtoTable = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnLoadfromFile = new javax.swing.JButton();
        btnSavetoFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JTableEmployee");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("ID");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Email:");

        jLabel5.setText("Phone");

        jLabel6.setText("Salary");

        jLabel7.setText("Job Position");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        btnAddtoTable.setBackground(new java.awt.Color(153, 255, 153));
        btnAddtoTable.setText("Add to Table");
        btnAddtoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddtoTableMouseClicked(evt);
            }
        });
        btnAddtoTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtoTableActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 255, 153));
        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        btnLoadfromFile.setBackground(new java.awt.Color(204, 102, 255));
        btnLoadfromFile.setForeground(new java.awt.Color(255, 255, 255));
        btnLoadfromFile.setText("Load from File");
        btnLoadfromFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoadfromFileMouseClicked(evt);
            }
        });

        btnSavetoFile.setBackground(new java.awt.Color(153, 255, 255));
        btnSavetoFile.setText("Save to File");
        btnSavetoFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSavetoFileMouseClicked(evt);
            }
        });

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "last Name", "PhoneNo.", "Email", "Salary", "Job Position"
            }
        ));
        tableData.setGridColor(new java.awt.Color(255, 255, 246));
        tableData.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tableData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSavetoFile, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSalary)
                                            .addComponent(txtJobPosition, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAddtoTable)
                            .addGap(28, 28, 28)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(565, 565, 565)
                            .addComponent(btnLoadfromFile, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtJobPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLoadfromFile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClear)
                            .addComponent(btnAddtoTable))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSavetoFile, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddtoTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtoTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddtoTableActionPerformed

    private void btnAddtoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddtoTableMouseClicked
        // TODO add your handling code here:
        Employee user = new Employee() ;
        user.setID(txtID.getText()) ;
        user.setFName(txtFirstName.getText()) ;
        user.setLName(txtLastName.getText()) ;
        user.setPhoneNo(txtPhoneNo.getText()) ;
        user.setEmail(txtEmail.getText()) ;
        user.setSalary(txtSalary.getText()) ;
        user.setJobPosition(txtJobPosition.getText()) ;
        UserList.add(user) ;
        
        DefaultTableModel model = (DefaultTableModel)tableData.getModel();
        
        model.addRow(new Object[0]);
        model.setValueAt(user.getID(),model.getRowCount()-1,0) ;
        model.setValueAt(user.getFName(),model.getRowCount()-1,1) ;
        model.setValueAt(user.getLName(),model.getRowCount()-1,2) ;
        model.setValueAt(user.getPhoneNo(),model.getRowCount()-1,3) ;
        model.setValueAt(user.getEmail(),model.getRowCount()-1,4) ;
        model.setValueAt(user.getSalary(),model.getRowCount()-1,5) ;
        model.setValueAt(user.getJobPosition(),model.getRowCount()-1,6) ;
    }//GEN-LAST:event_btnAddtoTableMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnLoadfromFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadfromFileMouseClicked
        // TODO add your handling code here:
        UserList = readUserDataFromFile() ;
        
        DefaultTableModel model = (DefaultTableModel)tableData.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged() ;
        for(Employee xRow : UserList)
        {            
        model.addRow(new Object[0]);
        model.setValueAt(xRow.getID(),model.getRowCount()-1,0) ;
        model.setValueAt(xRow.getFName(),model.getRowCount()-1,1) ;
        model.setValueAt(xRow.getLName(),model.getRowCount()-1,2) ;
        model.setValueAt(xRow.getPhoneNo(),model.getRowCount()-1,3) ;
        model.setValueAt(xRow.getEmail(),model.getRowCount()-1,4) ;
        model.setValueAt(xRow.getSalary(),model.getRowCount()-1,5) ;
        model.setValueAt(xRow.getJobPosition(),model.getRowCount()-1,6) ;
        }
    }//GEN-LAST:event_btnLoadfromFileMouseClicked

    private void btnSavetoFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSavetoFileMouseClicked
        // TODO add your handling code here:
        writeObjectToFile(UserList) ;
    }//GEN-LAST:event_btnSavetoFileMouseClicked

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UIMain().setVisible(true));
    }
    
    public boolean writeObjectToFile(List<Employee>userData)
    {
        String filePath = "C:\\Users\\Admins\\OneDrive\\HyperDus Develper\\CSBUY1\\CS318 Java OOP\\Week14\\JTableEmployee\\Employee.bin"  ;
        System.err.println("Save File Done " +filePath);
        
        try{
            
            
            FileOutputStream file = new FileOutputStream(filePath) ;
            ObjectOutputStream writer = new ObjectOutputStream(file) ;
            writer.writeObject(userData) ;
            writer.close() ;
            file.close() ;
            return true ;
        }catch(Exception ex)
        {
            System.err.println("failed to write " +filePath+","+ex);
            return false ;
        }
    }
    
    public List<Employee> readUserDataFromFile()
    {
         String filePath = "C:\\Users\\Admins\\OneDrive\\HyperDus Develper\\CSBUY1\\CS318 Java OOP\\Week14\\JTableEmployee\\Employee.bin" ;
         System.err.println("Load File Done " +filePath);
        
        try{
            FileInputStream file = new FileInputStream(filePath) ;
            ObjectInputStream reader = new ObjectInputStream(file) ;
            while(true)
            {
                try{
                    List<Employee>obj = (List<Employee>)reader.readObject() ;
                    return obj ;
                }catch(Exception ex){
                    System.err.println("end of read file");
                    break ;
                }
            }
        }catch(Exception ex)
        {
            System.err.println("failed to write " +filePath+","+ex);
        }
        return null ;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddtoTable;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnLoadfromFile;
    private javax.swing.JButton btnSavetoFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtJobPosition;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
