/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jtableguidemo;
import java.util.* ;
import java.io.* ;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class UIMain extends javax.swing.JFrame {
    public List<UserData>UserList = new ArrayList<>() ;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UIMain.class.getName());
    
    
    
    /**
     * Creates new form UIMain
     */
    public UIMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtPhoneNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnAddtoTable = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnLoadfromFile = new javax.swing.JButton();
        btnSavetoFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("PhoneNo.");

        jLabel4.setText("Email:");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        btnAddtoTable.setText("Add to Table");
        btnAddtoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddtoTableMouseClicked(evt);
            }
        });
        btnAddtoTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtoTableActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        btnLoadfromFile.setText("Load from File");
        btnLoadfromFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoadfromFileMouseClicked(evt);
            }
        });

        btnSavetoFile.setText("Save to File");
        btnSavetoFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSavetoFileMouseClicked(evt);
            }
        });

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "last Name", "PhoneNo.", "Email"
            }
        ));
        jScrollPane1.setViewportView(tableData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(txtPhoneNo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFirstName)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnAddtoTable)
                        .addGap(97, 97, 97)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179)
                        .addComponent(btnLoadfromFile)))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSavetoFile, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddtoTable)
                    .addComponent(btnClear)
                    .addComponent(btnLoadfromFile))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSavetoFile, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddtoTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtoTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddtoTableActionPerformed

    private void btnAddtoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddtoTableMouseClicked
        // TODO add your handling code here:
        UserData user = new UserData() ;
        user.setFName(txtFirstName.getText()) ;
        user.setLName(txtLastName.getText()) ;
        user.setPhoneNo(txtPhoneNo.getText()) ;
        user.setEmail(txtEmail.getText()) ;
        UserList.add(user) ;
        
        DefaultTableModel model = (DefaultTableModel)tableData.getModel();
        
        model.addRow(new Object[0]);
        model.setValueAt(user.getFName(),model.getRowCount()-1,0) ;
        model.setValueAt(user.getLName(),model.getRowCount()-1,1) ;
        model.setValueAt(user.getPhoneNo(),model.getRowCount()-1,2) ;
        model.setValueAt(user.getEmail(),model.getRowCount()-1,3) ;
    }//GEN-LAST:event_btnAddtoTableMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnLoadfromFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadfromFileMouseClicked
        // TODO add your handling code here:
        UserList = readUserDataFromFile() ;
        
        DefaultTableModel model = (DefaultTableModel)tableData.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged() ;
        for(UserData xRow : UserList)
        {            
        model.addRow(new Object[0]);
        model.setValueAt(xRow.getFName(),model.getRowCount()-1,0) ;
        model.setValueAt(xRow.getLName(),model.getRowCount()-1,1) ;
        model.setValueAt(xRow.getPhoneNo(),model.getRowCount()-1,2) ;
        model.setValueAt(xRow.getEmail(),model.getRowCount()-1,3) ;
        }
    }//GEN-LAST:event_btnLoadfromFileMouseClicked

    private void btnSavetoFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSavetoFileMouseClicked
        // TODO add your handling code here:
        writeObjectToFile(UserList) ;
    }//GEN-LAST:event_btnSavetoFileMouseClicked

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UIMain().setVisible(true));
    }
    
    public boolean writeObjectToFile(List<UserData>userData)
    {
        String filePath = "D:\\UserData.bin" ;
        
        try{
            
            
            FileOutputStream file = new FileOutputStream(filePath) ;
            ObjectOutputStream writer = new ObjectOutputStream(file) ;
            writer.writeObject(userData) ;
            writer.close() ;
            file.close() ;
            return true ;
        }catch(Exception ex)
        {
            System.err.println("failed to write " +filePath+","+ex);
            return false ;
        }
    }
    
    public List<UserData> readUserDataFromFile()
    {
         String filePath = "D:\\UserData.bin" ;
        
        try{
            FileInputStream file = new FileInputStream(filePath) ;
            ObjectInputStream reader = new ObjectInputStream(file) ;
            while(true)
            {
                try{
                    List<UserData>obj = (List<UserData>)reader.readObject() ;
                    return obj ;
                }catch(Exception ex){
                    System.err.println("end of read file");
                    break ;
                }
            }
        }catch(Exception ex)
        {
            System.err.println("failed to write " +filePath+","+ex);
        }
        return null ;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddtoTable;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnLoadfromFile;
    private javax.swing.JButton btnSavetoFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNo;
    // End of variables declaration//GEN-END:variables
}
