/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.examtest;

/**
 *
 * @author Admins
 */
public class MemberListSpy extends javax.swing.JInternalFrame {
    public static java.util.ArrayList<String[]> dataStore = new java.util.ArrayList<>();
    public static javax.swing.table.DefaultTableModel model;

    public MemberListSpy() {
        initComponents();
        model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    }
    /**
     * Creates new form MemberListSpy
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jButton1.setText("Reload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(255, 255, 254));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member ID", "First Name", "Last Name", "Member Class"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String filePath = "UserData.bin";
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    try {
            // 1. ตรวจสอบว่ามีไฟล์อยู่จริงไหม
            java.io.File f = new java.io.File(filePath);
            if (!f.exists()) {
                javax.swing.JOptionPane.showMessageDialog(this, "ไม่พบไฟล์ข้อมูล (UserData.bin)", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 2. เปิดไฟล์เพื่ออ่านข้อมูล
            java.io.FileInputStream fileIn = new java.io.FileInputStream(filePath);
            java.io.ObjectInputStream objectIn = new java.io.ObjectInputStream(fileIn);

            // 3. อ่าน Object ออกมาและแปลงกลับเป็น ArrayList
            // ต้อง Cast ให้ตรงกับตอนที่ Save (ArrayList<String[]>)
            Object obj = objectIn.readObject();
            java.util.ArrayList<String[]> loadedList = (java.util.ArrayList<String[]>) obj;
            
            // 4. อัปเดตตัวแปร dataStore ในความจำให้ตรงกับไฟล์ (สำคัญมาก! ไม่งั้นข้อมูลจะไม่ต่อเนื่อง)
            dataStore = loadedList;

            // 5. ล้างตารางเก่าแล้วใส่ข้อมูลใหม่
            model.setRowCount(0); 
            for (String[] row : dataStore) {
                model.addRow(row);
            }

            // ปิดการเชื่อมต่อไฟล์
            objectIn.close();
            fileIn.close();
            
            // javax.swing.JOptionPane.showMessageDialog(this, "โหลดข้อมูลเรียบร้อย!");

        } catch (Exception ex) {
            System.err.println("Error loading file: " + ex);
            javax.swing.JOptionPane.showMessageDialog(this, "เกิดข้อผิดพลาดในการโหลดไฟล์: " + ex.getMessage());
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
